MySQL:
  host: 'localhost'
  port: '3306'
  database: 'data'
  username: 'root'
  password: ''

#Координаты разных локаций
Locations:
  #Локация где игрок появляется после смерти
  respawn: 0,40,0
  #Спавн, где буду появляться новые игроки
  spawn: 0,65,0
  #Город "Бла-бла, хз как назвать"
  city1: 0,0,0
  #Город "Бла-бла, хз как назвать"
  city2: 0,0,0
  #Данж легкий
  dungeon_easy: 0,0,0
  #Данж средний
  dungeon_medium: 0,0,0
  #Данж сложный
  dungeon_hardcore: 0,0,0

